{
  "hash": "65076eba9e34ef077ae5c5b67193744c",
  "result": {
    "engine": "knitr",
    "markdown": "# Probabilistic Interpolation: Kriging\n\n\n\n::: {.cell}\n\n:::\n\n\n## Reading\nWe will finish Ch 8 in Bivand [@bivand2008geostatistics]. Sections 8.4 and 8.5 are the most important for this module. It's fairly dense after that. Review @fortin2016spatial as well, especially 4.3 to 4.5\n\n## Big Idea\nWe often want to estimate phenomena at locations where we do not have measurements. Geostatistics is the field that we use to make (hopefully) accurate and reliable models of spatial data. We will use these models for prediction. We can use both deterministic and probabilistic models and this module will focus on probabilistic methods. Kriging is a probabilistic method that finds spatial pattern and predicts unknown values based on that spatial pattern. Unlike IDW, kriging generates a measure of uncertainty allowing us to estimate confidence in the predictions.\n\n## Packages\nThe `gstat`[@R-gstat] package is your friend. And I'm going to plot in `ggplot` via `tidyverse`[@R-tidyverse] with `sf`[@R-sf], `terra`[@R-terra] and `tidyterra`[@R-tidyterra]. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(gstat)\nlibrary(tidyverse)\nlibrary(terra)\nlibrary(tidyterra)\n```\n:::\n\n\n## Some Kriging Theory\nIDW is a deterministic interpolation method. That is, it relies on a specified mathematical formula that is not a function of the statistical relationship among the known points. This method has no error term associated with it and in fact isn't really geostatistical in a strict sense. Now, you might like to have no error in your estimation but just because IDW doesn't spit out an error term doesn't mean that no error exists. A true geostatistical technique not only produces a prediction surface but also provides some measure of the accuracy of the predictions. Recall how  the names in the IDW objects we calculated had a blank column (`var1.var`)? That's where the error surface will be in addition to the predictions (`var1.pred`) as we move forward with a probabilistic approach to interpolation called Kriging. \n\nKriging is a geostatistical method of interpolation that uses spatial autocorrelation -- and it works best when there is strong autocorrelation in the data. When kriging we use the distance between sample points (and sometimes direction) to explain variation in a variable. We then fit a mathematical model to a specified number of points (or points within a certain distance) to determine the output value for each location. \n\nThe approach will make heavy use of the variograms that we started with earlier in the class. They are how we are going to determine the parameter $\\lambda$ in the formula for kriging:\n\n$$\\hat{Z}(s_0)=\\sum_{i=1}^n \\lambda_i Z(s_i)$$\n\nwhere $\\hat{Z}$ will be an estimate of a variable at a spatial location $s_0$ where we haven't measured $Z$ and $s_i$ a location, $i$, where we have measured $Z$. There are $n$ measurements. Analogous to the $w$ terms for IDW, $\\lambda_i$ is a weight for the measured value at location $s_i$. With IDW the weight was a deterministic function of distance. But with kriging, we use the distance between the measured points and the prediction location as well as the overall spatial structure of the measured points themselves. What is spatial structure? It's the spatial autocorrelation measured by the variogram. Let's review variograms.\n\n## Variogram Redux\nFitting a variogram is also called structural analysis and it is where we calculate the squared difference between the values of pairs of measured points. In the variogram we set this as $\\gamma = (z_i-z_j)^2/2$. We then plot $\\gamma$ against distance and we have a variogram cloud. In practice the number of pairs (dyads) to calculate and plot gets very large. For $n$ points there are $n \\cdot (n-1) / 2$ pairs. So, instead of plotting each pair we average $\\gamma$ by distance bins. This is the empirical semivariogram.\n\nWe will demonstrate a variogram with the `meuse` data. Here we load the meuse point data and the gridded data as `data.frame`, make a new variable by logging the `lead` column and plot them. This is the same procedure we used when doing IDW.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load\ndata(meuse.all)\nmeuse.grid <- readRDS(\"data/meuse.grid.Rds\")\n\n# make a variable to work with\nmeuse.all$logLead <- log(meuse.all$lead)\n# make into sf\nmeuse_sf <- st_as_sf(meuse.all, coords = c(\"x\", \"y\")) %>%\n  st_set_crs(value = 28992)\n\nmeuse_grid_sf <- st_as_sf(meuse.grid, \n                          coords = c(\"x\",\"y\"), \n                          crs = st_crs(meuse_sf))\nmeuse_grid_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3103 features and 5 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   part.a part.b       dist soil ffreq              geometry\n1       1      0 0.00000000    1     1 POINT (181180 333740)\n2       1      0 0.00000000    1     1 POINT (181140 333700)\n3       1      0 0.01222430    1     1 POINT (181180 333700)\n4       1      0 0.04346780    1     1 POINT (181220 333700)\n5       1      0 0.00000000    1     1 POINT (181100 333660)\n6       1      0 0.01222430    1     1 POINT (181140 333660)\n7       1      0 0.03733950    1     1 POINT (181180 333660)\n8       1      0 0.05936620    1     1 POINT (181220 333660)\n9       1      0 0.00135803    1     1 POINT (181060 333620)\n10      1      0 0.01222430    1     1 POINT (181100 333620)\n```\n\n\n:::\n\n```{.r .cell-code}\np1 <- ggplot(data = meuse_sf) +\n  geom_sf(aes(fill=logLead), size=4, \n          shape = 21, color=\"white\",alpha=0.8)+\n  scale_fill_continuous(type = \"viridis\",name=\"log(ppm)\") + \n  labs(title=\"Lead concentrations\")\np1\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nWe will use the `variogram` function in `gstat`. Look back at the autocorrelation module for review as needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadVar <- variogram(logLead~1, meuse_sf)\nplot(leadVar,pch=20,cex=1.5,col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"Lead concentrations (log(ppm))\")\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThis is the sample, or empirical, semivariogram. We interpret it as measurements that are closer together (left on the x-axis) have similar values (low values of $\\gamma$). As we move to pairs further apart (right on the x-axis) the semivariogram increases; values are more dissimilar and thus have a higher value of $\\gamma$. Our next job is going to be to fit a model to the points on the variogram. Before we do that, let's appreciate the three terms for describing the variogram.\n\n![](Variogram.gif)\n\n* The **range** is the distance beyond which the data are no longer correlated.\n* The **sill** is the variance of the variable.\n* The **nugget** is the autocorrelation at very small scales. The nugget represents independent error, measurement error and/or micro-scale variation at fine spatial scales. In a continuous variable we would expect that the nugget effect will be zero because at distance zero the values will be the same. However some variables can change in an abrupt manner and so in very short distance there is a difference.\n\nIf there is no structure (no correlation) and the variable is therefore a purely random variable, the variogram will be flat with a nugget effect.\n\n## Variogram Model\n\nAfter plotting the **sample** variogram we can then fit a statistical **model** to the points. The model is a continuous estimate of $\\gamma$ as a function of distance: $\\hat{\\gamma}=f(d)$.  \n\nWe will fit two different functions a spherical model and an exponential model. The text has descriptions of the various functions. in practice, we tend to look at the general shape of the plot and then choose a mathematical model that fits.\n\nNote that `gstat` uses the partial sill (`psill`) which is the sill minus the nugget. Just to be confusing. Thanks `gstat`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note our initial estimates for the partial sill, range, and nugget. \nsph.model <- vgm(psill=0.5, model=\"Sph\", range=750, nugget=0.05)\nsph.fit <- fit.variogram(object = leadVar, model = sph.model)\nsph.fit # look at the fitted values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  model     psill    range\n1   Nug 0.1095742    0.000\n2   Sph 0.4560318 1002.626\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(leadVar,model=sph.fit,pch=20,cex=1.5,col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"Lead concentrations (log(ppm))\",\n     sub=\"Points: Empirical, Line: Spherical Model\")\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe now have a fitted, theoretical, variogram model to the data in the `sph.fit` object. This object took our estimates of the partial sill, range, and nugget and found the best fits from those estimates using non-linear regression. The final parameters are pretty close to our estimates from the plot. E.g., the fitted nugget is 0.11 and the range is 1002.63. If we gave initial estimates way outside the realm of possibility the function wouldn't be able to fit the model. But if the data are well behaved it converges on the best fit pretty easily. If you are too scared to estimate initial values in `vgm` the function will estimate them for you. See Details under `?fit.variogram` for how those are calculated. E.g., in this application if you try `sph.model <- vgm(model=\"Sph\",nugget=TRUE)` the `fit.variogram` algorithm converges without initial estimates.\n\nThe actual function for the spherical model is:\n\n$$\\hat{\\gamma}(d)= b + C_0 \\left(1.5\\left(\\frac{d}{r}\\right) - 0.5 \\left(\\frac{d^3}{r}\\right)\\right)$$\n\nwhere $b$ is the nugget, $C_0$ is the sill, $d$ is the distance, and $r$ is the range.\n\nThe spherical model above is very commonly used and has nice theoretical properties, using all three classic parameters of the variogram. We could, if we liked, fit some other models -- an exponential model would fit well here too. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# note our initial estimates for the sill, range, and nugget\nexp.model <- vgm(psill=0.5, model=\"Exp\", range=750, nugget=0.05)\nexp.fit <- fit.variogram(object = leadVar, model = exp.model)\nplot(leadVar,model=exp.fit,pch=20,cex=1.5,col=\"black\",\n     ylab=expression(\"Semivariance (\"*gamma*\")\"),\n     xlab=\"Distance (m)\", main = \"Lead concentrations (log(ppm))\",\n     sub=\"Points: Empirical, Line: Exponential Model\")\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis model is $\\hat{\\gamma}(d)=b + C_0(1-e^{-d/a})$ where $a=r/3$ and other terms are as above. \n\n## Putting it Together\nWe have a fitted variogram model now. That is $\\hat{\\gamma}(d)$ or an estimate of spatial structure at any distance. Here is our Kriging formula again:\n\n$$\\hat{Z}(s_0)=\\sum_{i=1}^n \\lambda_i Z(s_i)$$\n\nHow do we get to the weights ($\\lambda$)? From the variogram model. The guts of this calculation involve a little matrix algebra to fully work through, but conceptually it is pretty simple: \n$$ \\lambda = \\Gamma^{-1} g $$\n\nwhere $\\Gamma$ is matrix of the semivariance for all sampled point pairs predicted as a function of their Euclidean distance using the fitted variogram model and $g$ is a vector of predicted semivariances for the unknown points using their Euclidean distances from the known points. Once we have $\\lambda$ we can interpolate (predict) over a surface for any location where we don't have $Z$. Or, $\\hat{Z}(s_0)$.\n\n## Toy Example\nLike we did with IDW, let's walk through this calculation with a contrived example.\n\n### Data\nNow that we have the information we need on the algorithm, let's do a quick and dirty example by hand to walk through some of the calculations. \n\nHere is a small data set of five points. We have spatial coordinates ($x$ and $y$) and some measured variable ($z$).\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo <- data.frame(x = c(1,3,1,4,5),\n                  y = c(5,4,3,5,1),\n                  z = c(100,105,105,100,115))\nfoo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x y   z\n1 1 5 100\n2 3 4 105\n3 1 3 105\n4 4 5 100\n5 5 1 115\n```\n\n\n:::\n\n```{.r .cell-code}\np2 <- ggplot() + \n  geom_point(data=foo,aes(x=x,y=y,size=z)) + \n  lims(x=c(0,6),y=c(0,6))\np2\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nLet's imagine a point $x=2$ and $y=4$ where we don't know $z$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- p2 + \n  geom_point(aes(x=2,y=4),color=\"red\",size=10,shape=0) +\n  geom_point(aes(x=2,y=4),color=\"red\",size=6,shape=63)\np2\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Interpolate with Kriging\nWe are now going to use Kriging as a way to get an estimate of that point with a missing value of $z$. Since we are estimating it we call it $\\hat{Z}$ and we know the location as $s_0$ so we call this $\\hat{Z}(s_0)$. We'll follow the notation above.\n\nThe Euclidean distance to our unknown point from each of the known points is a vector: \n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{d_i} = \\left[\\begin{array}\n{rr}\n1 & 1.414\\\\\n2 & 1.000\\\\\n3 & 1.414\\\\\n4 & 2.236\\\\\n5 & 4.243\n\\end{array}\\right]$$\n\n\n\nTo get $\\hat{Z}(s_0)$ we need to calculate $\\lambda$ and you will recall how we do that, right? We fit a variogram plotting semivariance ($\\gamma$) against distance ($d$) and get the function that predicts $\\gamma$. Now, these five data points we have don't actually make a nice variogram. So let's suspend disbelief for a moment and I'll tell you that the variogram model is $\\hat{\\gamma} = 0 + 13.5(d)$. Cool?\n\nHow do we get to the weights ($\\lambda$)? The guts of this calculation involve a little matrix algebra to fully work through, but conceptually it is pretty simple: \n$$ \\lambda = g \\Gamma^{-1} $$\n\nwhere $\\Gamma$ is matrix of the semivariance for all sampled point pairs predicted as a function of their Euclidean distance using the fitted variogram model and $g$ is a vector of predicted semivariances for the unknown points using their Euclidean distances from the known points. Once we have $\\lambda$ we can now interpolate (predict) over a surface.\n\nFirst we can calculate $g$ for the point we want to interpolate. We'll do the same point that we did above with IDW. Thus, $g=0 + 13.5(d_i)$: \n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{g} = \\left[\\begin{array}\n{rr}\n1 & 19.09\\\\\n2 & 13.50\\\\\n3 & 19.09\\\\\n4 & 30.19\\\\\n5 & 57.28\n\\end{array}\\right]$$\n\nNow, let's get $\\Gamma$. First, here is the distance matrix between all the measured points:\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{d} = \\left[\\begin{array}\n{rrrrr}\n~ & 1 & 2 & 3 & 4 \\\\\n2 & 2.236 & ~ & ~ & ~ \\\\\n3 & 2.000 & 2.236 & ~ & ~ \\\\\n4 & 3.000 & 1.414 & 3.606 & ~ \\\\\n5 & 5.657 & 3.606 & 4.472 & 4.123\n\\end{array}\\right]$$\n\nWe multiply this by the the variogram model $\\hat{\\gamma}(d)$:\n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{\\Gamma} = \\left[\\begin{array}\n{rrrrr}\n~ & 1 & 2 & 3 & 4 \\\\\n2 & 30.19 & ~ & ~ & ~ \\\\\n3 & 27.00 & 30.19 & ~ & ~ \\\\\n4 & 40.50 & 19.09 & 48.67 & ~ \\\\\n5 & 76.37 & 48.67 & 60.37 & 55.66\n\\end{array}\\right]$$\n\nWe now need the inverse of $\\Gamma$. Inverting a matrix bigger than say 2x2 is not something I want to do by hand. Inverting a 5x5 matrix by hand would take me all day and I'd definitely screw it up. If you can't recall how to invert a matrix you can check out the always helpful Kahn Academy's take on it [here](https://www.khanacademy.org/math/precalculus/precalc-matrices/intro-to-matrix-inverses/v/inverse-matrix-part-1). In R you can use the `solve` function (or `ginv` in the `MASS` package) to invert a matrix.\n\n\n::: {.cell}\n\n:::\n\n\n$$\\mathbf{\\Gamma^{-1}} = \\left[\\begin{array}\n{rrrrr}\n~ & 1      & 2      & 3      & 4      & 5     \\\\\n1 & -0.023 & 0.005  & 0.017  & 0.009  & 0.000  \\\\\n2 & 0.005  & -0.045 & 0.010  & 0.021  & 0.003  \\\\\n3 & 0.017  & 0.010  & -0.026 & -0.003 & 0.007  \\\\\n4 & 0.009  & 0.021  & -0.003 & -0.027 & 0.007  \\\\\n5 & 0.000  & 0.003  & 0.007  & 0.007  & -0.007\n\\end{array}\\right]$$\n\nAnd $\\lambda = g~\\Gamma^{-1}$:\n$$\\mathbf{\\lambda_i} = \\left[\\begin{array}\n{rr}\n1 & 0.244\\\\\n2 & 0.491\\\\\n3 & 0.256\\\\\n4 & -0.013\\\\\n5 & -0.028\n\\end{array}\\right]$$\n\n\nGiving the final prediction:\n$$\\hat{Z}(s_0)=0.244(100)+0.491(105)+0.256(105)-0.013(100)-0.028(115)=98.3$$\n\nThe matrix notation can be sort of tedious but hopefully you've gotten the idea that because of the theoretical variogram model we can estimate $\\hat{\\gamma}$ for any distance $d$ and use that information with the observed distance matrix to predict $Z$ at any location ($\\hat{Z}(s_0)$).\n\n## Application: Kriging a Lead Surface\nThis will look a lot like what we did with IDW but we will use `krige` instead. And `krige` wants a fitted variogram model to be passed in. So, using the variogram from above we can do this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadVar <- variogram(logLead~1, meuse_sf)\nleadModel <- vgm(psill=0.6, model=\"Sph\", range=750, nugget=0.05)\nleadFit <- fit.variogram(object = leadVar, model = leadModel)\nleadGstat <- gstat(formula = logLead~1, locations = meuse_sf, \n                   model = leadFit)\nleadKrige_sf <- predict(leadGstat,newdata = meuse_grid_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[using ordinary kriging]\n```\n\n\n:::\n\n```{.r .cell-code}\nleadKrige_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3103 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   var1.pred  var1.var              geometry\n1   5.336713 0.3183947 POINT (181180 333740)\n2   5.406841 0.2724001 POINT (181140 333700)\n3   5.343480 0.2854597 POINT (181180 333700)\n4   5.279198 0.3003649 POINT (181220 333700)\n5   5.486278 0.2238744 POINT (181100 333660)\n6   5.415401 0.2377063 POINT (181140 333660)\n7   5.339935 0.2536512 POINT (181180 333660)\n8   5.266665 0.2701756 POINT (181220 333660)\n9   5.562294 0.1801611 POINT (181060 333620)\n10  5.496279 0.1894106 POINT (181100 333620)\n```\n\n\n:::\n:::\n\n\nNote that `leadKrige` is a `sf` object that has the predicted surface `var1.pred` but there is another surface in there too `var1.var` which contains the variance around those predictions. Let's take a look at the predictions first and then we can think more about how that `var1.var` surface came to be.\n\nHere is the prediction surface. Note how we specify what `attribute` we want to plot to plot via `leadKrige[\"var1.pred\"]`.\n\nI'll use the little function from the IDW notes to get a `rast` object from the `sf` object.\n\n::: {.cell}\n\n```{.r .cell-code}\nsf_2_rast <-function(sfObject,variableIndex = 1){\n  # coerce sf to a data.frame\n  dfObject <- data.frame(st_coordinates(sfObject),\n                         z=as.data.frame(sfObject)[,variableIndex])\n  # coerce data.frame to SpatRaster\n  rastObject <- rast(dfObject,crs=crs(sfObject))\n  \n  names(rastObject) <- names(sfObject)[variableIndex]\n  \n  return(rastObject)\n}\n\nleadKrige_rast <- sf_2_rast(leadKrige_sf)\n\nleadKrige_rast\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \nsize        : 104, 78, 1  (nrow, ncol, nlyr)\nresolution  : 40, 40  (x, y)\nextent      : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)\ncoord. ref. : Amersfoort / RD New (EPSG:28992) \nsource(s)   : memory\nname        : var1.pred \nmin value   :  3.749342 \nmax value   :  6.174216 \n```\n\n\n:::\n\n```{.r .cell-code}\n# and plot\nggplot() +\n  geom_spatraster(data=leadKrige_rast, mapping = aes(fill=var1.pred),alpha=0.8) +\n  scale_fill_continuous(type = \"viridis\",name=\"log(ppm)\",na.value = \"transparent\") + \n  labs(title=\"Lead concentrations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\nNow let's look at the variance around those predictions. Note we take the square root of `var1.var` to get the uncertainty in the same units as `var1.pred`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadKrige_sf$var1.var.sqrt <- sqrt(leadKrige_sf$var1.var)\n\nleadKrige_rast <- sf_2_rast(leadKrige_sf,variableIndex = 4)\nleadKrige_rast\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \nsize        : 104, 78, 1  (nrow, ncol, nlyr)\nresolution  : 40, 40  (x, y)\nextent      : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)\ncoord. ref. : Amersfoort / RD New (EPSG:28992) \nsource(s)   : memory\nname        : var1.var.sqrt \nmin value   :     0.3881239 \nmax value   :     0.6503917 \n```\n\n\n:::\n\n```{.r .cell-code}\n# and plot\nggplot() +\n  geom_spatraster(data=leadKrige_rast, mapping = aes(fill=var1.var.sqrt ),alpha=0.8) +\n  scale_fill_continuous(type = \"viridis\",name=\"log(ppm)\",na.value = \"transparent\") + \n  labs(title=\"Variance of lead concentrations\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nAs you can see, kriging generates a measure of error or uncertainty for the predictions. This means that you can estimate confidence in the prediction surface and compare it to a random expectation. How does that all work? Well, it's more than I wanted to get into in the \"by hand' calculation above so I'll summarize it below. \n\n## Uncertainty\nThe various variogram models we looked at above (i.e., spherical and exponential) and ones we didn't (e.g., Gaussian and Mattern) are more than just pretty lines that we use to get a continuous model of $\\hat{\\gamma}$ as a function of distance. They have some of the same [properties](https://en.wikipedia.org/wiki/Variogram#Properties) that statistical distributions have in regards to probability theory. In particular, variograms are empirical estimates of the covariance of Gaussian processes. As the model variogram gives the mean of the squared differences between values based on their location, the uncertainty in the variogram at a given distance is the average covariance between \"pairs of pairs\" used to calculate the variogram. This covariance follows a Gaussian process and thus allows each estimate (prediction) to have an associated error distribution which `gstat` reports as the variance. The underlying theory is well beyond what we cover here but a geostats book like Diggle's [\"Model-based Geostatistics\"](https://books.google.com/books/about/Model_based_Geostatistics.html?id=qCqOm39OuFUC) will drag you through it. Bivand's chapter has more on this of course and I'll link to a walk through of calculating the uncertainty on a separate page.\n\n## Other Variogram Models\nAbove I showed you the Gaussian and the exponential variogram models. Those are commonly used as are the Mattern model and the Spherical model. But there are many other options. There are a whole slew actually most of which I've never used. Look at this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvgm()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   short                                      long\n1    Nug                              Nug (nugget)\n2    Exp                         Exp (exponential)\n3    Sph                           Sph (spherical)\n4    Gau                            Gau (gaussian)\n5    Exc        Exclass (Exponential class/stable)\n6    Mat                              Mat (Matern)\n7    Ste Mat (Matern, M. Stein's parameterization)\n8    Cir                            Cir (circular)\n9    Lin                              Lin (linear)\n10   Bes                              Bes (bessel)\n11   Pen                      Pen (pentaspherical)\n12   Per                            Per (periodic)\n13   Wav                                Wav (wave)\n14   Hol                                Hol (hole)\n15   Log                         Log (logarithmic)\n16   Pow                               Pow (power)\n17   Spl                              Spl (spline)\n18   Leg                            Leg (Legendre)\n19   Err                   Err (Measurement error)\n20   Int                           Int (Intercept)\n```\n\n\n:::\n:::\n\n\n`gtsat` knows 20 different possible curves you can fit to your data. E.g.,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow.vgms(models = c(\"Exp\", \"Mat\", \"Gau\", \"Sph\"))\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nVariogram functions are central to geostatistics and particularly to Kriging. The properties and characteristics of variogram functions that make them well-suited for such applications include:\n\n**Non-Negativity**: Variogram functions must be non-negative, which ensures that the measure of spatial variability (semi-variance) between pairs of points is always a non-negative value. This property is essential.\n\n**Definiteness (Positive Semi-Definiteness)**: For Kriging to produce valid estimates, the variogram must result in a positive semi-definite covariance matrix. This property ensures that the estimated variances are always non-negative, making the Kriging system solvable and ensuring that the weights derived during Kriging are valid and stable.\n\n**Continuity and Differentiability**: Many variogram models are continuous and differentiable, which helps in providing smooth estimates. This is particularly important for interpolation where smooth transitions between estimated values are desirable.\n\n**Model Flexibility**: Different variogram models (spherical, Gaussian, exponential, etc.) offer flexibility in capturing various types of spatial structures. Each model has a different shape and range, allowing them to fit different patterns of spatial correlation:\n   - **Spherical Model**: Often used for phenomena where spatial correlation decreases uniformly and becomes zero at a certain range.\n   - **Gaussian Model**: Suitable for processes with a high degree of continuity and smooth transitions.\n   - **Exponential Model**: Useful for capturing short-range spatial correlations that decrease rapidly with distance.\n\n**Asymptotic Behavior**: Variogram models often approach a sill, representing the maximum variability (or variance) beyond a certain distance (range). This property helps in defining the limit beyond which spatial dependence between points can be considered negligible.\n\n**Practical Interpretability**: Variogram models have parameters (such as nugget, sill, and range) that are interpretable and can be related to the physical characteristics of the spatial process. This interpretability aids in understanding the underlying spatial structure and making informed decisions.\n\nThe appropriate choice of a variogram model directly influences the accuracy and reliability of the Kriging estimates. There is no one-size-fits all approach.\n\n\n## Other Types of Kriging\nWe are just scratching the surface of what we can do with kriging. Think about what you might do in terms of interpolating in the presence of a trend?  Or how to model anisotropy (see the `anis` argument to `vgm`). As with many topics in this class you could spend a whole quarter on kriging alone.\n\n## Cross Validation\nI showed an example of using the built in cross validation function at the end of the last module. We can do the same with kriging. Instead of a straight call to `krige` we can call `krige.cv` for either k-fold or leave-one-out cross validation (LOOCV). It defaults to LOOCV so the predicted values are from the time they were left out the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadKrigeLOOCV_sf <- krige.cv(formula = logLead~1, \n                           locations = meuse_sf, \n                           model = leadFit, verbose = FALSE)\nleadKrigeLOOCV_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 164 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611\nProjected CRS: Amersfoort / RD New\nFirst 10 features:\n   var1.pred  var1.var observed    residual       zscore fold\n1   5.402571 0.2277973 5.700444  0.29787270  0.624103170    1\n2   5.473044 0.2199374 5.624018  0.15097361  0.321922586    2\n3   5.233697 0.2180910 5.293305  0.05960821  0.127640125    3\n4   5.077189 0.2520550 4.753590 -0.32359847 -0.644553277    4\n5   4.794539 0.2134651 4.762174 -0.03236554 -0.070051822    5\n6   4.584552 0.2571416 4.919981  0.33542860  0.661475718    6\n7   4.970576 0.2088842 4.882802 -0.08777385 -0.192049137    7\n8   5.253444 0.2072102 5.010635 -0.24280892 -0.533407471    8\n9   4.886148 0.1786532 4.890349  0.00420153  0.009940359    9\n10  4.589513 0.1984181 4.382027 -0.20748612 -0.465798826   10\n                geometry\n1  POINT (181072 333611)\n2  POINT (181025 333558)\n3  POINT (181165 333537)\n4  POINT (181298 333484)\n5  POINT (181307 333330)\n6  POINT (181390 333260)\n7  POINT (181165 333370)\n8  POINT (181027 333363)\n9  POINT (181060 333231)\n10 POINT (181232 333168)\n```\n\n\n:::\n\n```{.r .cell-code}\n# CV R2\ncor(leadKrigeLOOCV_sf$observed,leadKrigeLOOCV_sf$var1.pred)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6192935\n```\n\n\n:::\n:::\n\n\nThe LOOCV R$^2$ is 0.6193 which we get from the observed vs predicted values. But note all the fields we get from the `krige.cv` function. We get the prediction and prediction variance of the cross-validated data points and we also get the observed values.  But we also get the residuals (observed minus predicted), the z-score (the residual divided by kriging standard error), and the fold (in this case we have as many folds as rows in meuse because it is LOOCV).\n\n## Your Work\nLet's turn again to the California precipitation data that you used for the IDW module. Like with IDW, you'll make a continuous 10x10 km surface of precipitation from the 432 locations of long-term precipitation records. But this time you'll krige the surface rather than use IDW.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# precip point data\nprcpCA <- readRDS(\"data/prcpCA.rds\")\n# empty grid to interpolate into\ngridCA <- readRDS(\"data/gridCA.rds\")\n\nprcpCAsf <- prcpCA %>% st_as_sf(coords = c(\"X\", \"Y\")) %>%\n  st_set_crs(value = 3310)\n\nprcpCAsf %>% ggplot() + \n  geom_sf(aes(fill=ANNUAL,size=ANNUAL),color=\"white\",\n          shape=21,alpha=0.8) + \n  scale_fill_continuous(type = \"viridis\",name=\"mm\") + \n  labs(title=\"Total Annual Precipitation\") +\n  scale_size(guide=\"none\")\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nUse kriging to create a surface of total annual precipitation in California -- do not use `automap` but fit the models using `variogram`, `vgm`, and `fit.variogram` as above. Compare at least two variogram models and assess the surface fit in a sensible way. Interpret and explain your surface and anything you notice in particular about it. \n\n## Postscript: Automap\nYou'll find it anyways, so let's get the cat out of the bag.\n\nLike other angry old men, I like to describe a bucolic youth spent milking at 4AM, walking to school in the snow, programming F77 in vi, and **doing all my GIS with Arc on the command line**. Kids these days like to do their geostatistics in ArcGIS by clicking \"next, next, next, finish\" and plotting their map without `ARCPLOT`. One of the many reasons I like using `R` is that you get to do things like fit variograms by hand the same way the pioneers did when they had to cross the prairie. But you can, if you like, automatically fit a variogram using the `automap` library which has a lot of nice wrappers for the `gstat` functions like `fit.variogram`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(automap)\nleadVar <- autofitVariogram(formula = logLead~1,input_data = meuse_sf)\nsummary(leadVar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExperimental variogram:\n     np       dist     gamma dir.hor dir.ver   id\n1    17   59.33470 0.1270576       0       0 var1\n2    39   86.73182 0.1905754       0       0 var1\n3   126  130.83058 0.1487020       0       0 var1\n4   171  176.60188 0.2540911       0       0 var1\n5   198  226.70319 0.2378083       0       0 var1\n6   810  338.36102 0.3395189       0       0 var1\n7   957  502.89504 0.4191339       0       0 var1\n8  1580  712.92647 0.5180130       0       0 var1\n9  1500  961.00617 0.5738388       0       0 var1\n10 1301 1212.86100 0.5675023       0       0 var1\n11 1517 1504.85947 0.4954516       0       0 var1\n\nFitted variogram model:\n  model      psill    range\n1   Nug 0.09182989   0.0000\n2   Sph 0.46323373 941.6887\nSums of squares betw. var. model and sample var.[1] 2.920612e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(leadVar)\n```\n\n::: {.cell-output-display}\n![](06aGeostatsKriging_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThis automatically fits and plots a variogram like `fit.variogram` but instead of using user-supplied initial estimates for the model and the parameters, `autofitVariogram` makes these estimates based on the data and then calls `fit.variogram`. The automatic fitting above chose a spherical model like we did above but it tried all the models (exponential, Gaussian, Mattern, etc.) as part of the process.\n\nThe biggest difference is that `autofitVariogram` does the bins quite differently than `gstat`'s default behavior with `variogram`. Instead of equal lengths, `autofitVariogram` creates bin of unequal widths. It passes these as the  `boundaries`  argument to `variogram`. You can look at the code for details (`getAnywhere(autofitVariogram)`) but the spirit is to try to get more leverage on the shortest distances to help estimate the wiggliest part of the variogram curve -- esp the nugget. I think it makes sense.\n\nNote that this plot (which is invoked for objects of class `autofitVariogram`) plots the number of point pairs at that distance as well as adds the model terms as a legend. You can look at the code for this plot via `getAnywhere(plot.autofitVariogram)` if you are curious.\n\nAnd just to complete the whole automation thing, you can automatically apply cross validation as well. Since `autoKrige.cv` calls `krige.cv` to do a lot of the work, it defaults to LOOCV as above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleadAutoKrigeLOOCV <- autoKrige.cv(formula = logLead~1, input_data = meuse_sf,\n                                   verbose = c(FALSE,FALSE))\nsummary(leadAutoKrigeLOOCV)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]      \nmean_error  -0.002369 \nme_mean     -0.0004967\nMAE         0.2996    \nMSE         0.1692    \nMSNE        0.8531    \ncor_obspred 0.7901    \ncor_predres 0.04327   \nRMSE        0.4113    \nRMSE_sd     0.6117    \nURMSE       0.4113    \niqr         0.4022    \n```\n\n\n:::\n\n```{.r .cell-code}\n# R2\ncor(leadAutoKrigeLOOCV$krige.cv_output$observed,leadAutoKrigeLOOCV$krige.cv_output$var1.pred)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6242166\n```\n\n\n:::\n:::\n\n\nHere we get a LOOCV R$^2$ of 0.6242 which is very (very) close to what we got with the cross validation we did manually above.\n\n**Use the tools in `automap` with caution however. Beware the black box.**",
    "supporting": [
      "06aGeostatsKriging_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}