<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9 Probabilistic Interpolation: Regression Kriging | Spatial Analysis for Environmental Science</title>
  <meta name="description" content="Spatial analysis notes and exercises" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="9 Probabilistic Interpolation: Regression Kriging | Spatial Analysis for Environmental Science" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Spatial analysis notes and exercises" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 Probabilistic Interpolation: Regression Kriging | Spatial Analysis for Environmental Science" />
  
  <meta name="twitter:description" content="Spatial analysis notes and exercises" />
  

<meta name="author" content="Andy Bunn" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probabilistic-interpolation-kriging.html"/>
<link rel="next" href="aside-kriging-variance-by-hand.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.3/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#whats-in-these-notes"><i class="fa fa-check"></i><b>1.1</b> What’s in These Notes</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#go-do-great-things"><i class="fa fa-check"></i><b>1.2</b> Go Do Great Things</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#technical-setup"><i class="fa fa-check"></i><b>1.3</b> Technical Setup</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#project-structure"><i class="fa fa-check"></i><b>1.3.1</b> Project Structure</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-getting-your-bearings.html"><a href="introduction-getting-your-bearings.html"><i class="fa fa-check"></i><b>2</b> Introduction: Getting Your Bearings</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-getting-your-bearings.html"><a href="introduction-getting-your-bearings.html#big-idea"><i class="fa fa-check"></i><b>2.1</b> Big Idea</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-getting-your-bearings.html"><a href="introduction-getting-your-bearings.html#your-toolkit-for-the-course"><i class="fa fa-check"></i><b>2.2</b> Your Toolkit for the Course</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-getting-your-bearings.html"><a href="introduction-getting-your-bearings.html#your-work"><i class="fa fa-check"></i><b>2.3</b> Your Work</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html"><i class="fa fa-check"></i>Aside: Understanding Methods and Generics in R</a>
<ul>
<li class="chapter" data-level="2.4" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#youve-come-a-long-way-in-r"><i class="fa fa-check"></i><b>2.4</b> You’ve Come a Long Way in R</a></li>
<li class="chapter" data-level="2.5" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#why-use-generics"><i class="fa fa-check"></i><b>2.5</b> Why Use Generics?</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#same-function-different-behavior.-what-gives"><i class="fa fa-check"></i><b>2.5.1</b> Same Function, Different Behavior. What Gives?</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#how-this-works"><i class="fa fa-check"></i><b>2.6</b> How This Works</a></li>
<li class="chapter" data-level="2.7" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#whats-the-difference-between-a-generic-and-a-method"><i class="fa fa-check"></i><b>2.7</b> What’s the Difference Between a Generic and a Method?</a></li>
<li class="chapter" data-level="2.8" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#common-generic-functions"><i class="fa fa-check"></i><b>2.8</b> Common Generic Functions</a></li>
<li class="chapter" data-level="2.9" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#how-to-explore-and-understand-methods"><i class="fa fa-check"></i><b>2.9</b> How to Explore and Understand Methods</a></li>
<li class="chapter" data-level="2.10" data-path="aside-understanding-methods-and-generics-in-r.html"><a href="aside-understanding-methods-and-generics-in-r.html#why-this-matters"><i class="fa fa-check"></i><b>2.10</b> Why This Matters</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mt-baker-map.html"><a href="mt-baker-map.html"><i class="fa fa-check"></i><b>3</b> Mt Baker Map</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mt-baker-map.html"><a href="mt-baker-map.html#big-idea-1"><i class="fa fa-check"></i><b>3.1</b> Big Idea</a></li>
<li class="chapter" data-level="3.2" data-path="mt-baker-map.html"><a href="mt-baker-map.html#packages"><i class="fa fa-check"></i><b>3.2</b> Packages</a></li>
<li class="chapter" data-level="3.3" data-path="mt-baker-map.html"><a href="mt-baker-map.html#prepratory-work"><i class="fa fa-check"></i><b>3.3</b> Prepratory Work</a></li>
<li class="chapter" data-level="3.4" data-path="mt-baker-map.html"><a href="mt-baker-map.html#introduction"><i class="fa fa-check"></i><b>3.4</b> Introduction</a></li>
<li class="chapter" data-level="3.5" data-path="mt-baker-map.html"><a href="mt-baker-map.html#the-data"><i class="fa fa-check"></i><b>3.5</b> The Data</a></li>
<li class="chapter" data-level="3.6" data-path="mt-baker-map.html"><a href="mt-baker-map.html#a-map"><i class="fa fa-check"></i><b>3.6</b> A Map</a></li>
<li class="chapter" data-level="3.7" data-path="mt-baker-map.html"><a href="mt-baker-map.html#your-work-1"><i class="fa fa-check"></i><b>3.7</b> Your work</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="point-patterns.html"><a href="point-patterns.html"><i class="fa fa-check"></i><b>4</b> Point Patterns</a>
<ul>
<li class="chapter" data-level="4.1" data-path="point-patterns.html"><a href="point-patterns.html#big-idea-2"><i class="fa fa-check"></i><b>4.1</b> Big Idea</a></li>
<li class="chapter" data-level="4.2" data-path="point-patterns.html"><a href="point-patterns.html#reading"><i class="fa fa-check"></i><b>4.2</b> Reading</a></li>
<li class="chapter" data-level="4.3" data-path="point-patterns.html"><a href="point-patterns.html#packages-1"><i class="fa fa-check"></i><b>4.3</b> Packages</a></li>
<li class="chapter" data-level="4.4" data-path="point-patterns.html"><a href="point-patterns.html#point-patterns-1"><i class="fa fa-check"></i><b>4.4</b> Point Patterns</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="point-patterns.html"><a href="point-patterns.html#simulated-example"><i class="fa fa-check"></i><b>4.4.1</b> Simulated Example</a></li>
<li class="chapter" data-level="4.4.2" data-path="point-patterns.html"><a href="point-patterns.html#data"><i class="fa fa-check"></i><b>4.4.2</b> Data</a></li>
<li class="chapter" data-level="4.4.3" data-path="point-patterns.html"><a href="point-patterns.html#kernel-density-estimation"><i class="fa fa-check"></i><b>4.4.3</b> Kernel Density Estimation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="point-patterns.html"><a href="point-patterns.html#ripleys-k"><i class="fa fa-check"></i><b>4.5</b> Ripley’s K</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="point-patterns.html"><a href="point-patterns.html#distances-and-edges"><i class="fa fa-check"></i><b>4.5.1</b> Distances and edges</a></li>
<li class="chapter" data-level="4.5.2" data-path="point-patterns.html"><a href="point-patterns.html#l-hat"><i class="fa fa-check"></i><b>4.5.2</b> L hat</a></li>
<li class="chapter" data-level="4.5.3" data-path="point-patterns.html"><a href="point-patterns.html#marked-point-patterns"><i class="fa fa-check"></i><b>4.5.3</b> Marked point patterns</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="point-patterns.html"><a href="point-patterns.html#roll-your-own"><i class="fa fa-check"></i><b>4.6</b> Roll your own</a></li>
<li class="chapter" data-level="4.7" data-path="point-patterns.html"><a href="point-patterns.html#more-than-trees"><i class="fa fa-check"></i><b>4.7</b> More than trees</a></li>
<li class="chapter" data-level="4.8" data-path="point-patterns.html"><a href="point-patterns.html#your-work-2"><i class="fa fa-check"></i><b>4.8</b> Your Work</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="point-patterns.html"><a href="point-patterns.html#simulated-data"><i class="fa fa-check"></i><b>4.8.1</b> Simulated data</a></li>
<li class="chapter" data-level="4.8.2" data-path="point-patterns.html"><a href="point-patterns.html#mycorrhizal-fungi"><i class="fa fa-check"></i><b>4.8.2</b> Mycorrhizal fungi</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="point-patterns.html"><a href="point-patterns.html#extra-rolling-k-by-hand"><i class="fa fa-check"></i><b>4.9</b> Extra: Rolling K by Hand</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html"><i class="fa fa-check"></i><b>5</b> Spatial Autocorrelation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#big-idea-3"><i class="fa fa-check"></i><b>5.1</b> Big Idea</a></li>
<li class="chapter" data-level="5.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#reading-1"><i class="fa fa-check"></i><b>5.2</b> Reading</a></li>
<li class="chapter" data-level="5.3" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#packages-2"><i class="fa fa-check"></i><b>5.3</b> Packages</a></li>
<li class="chapter" data-level="5.4" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#preamble"><i class="fa fa-check"></i><b>5.4</b> Preamble</a></li>
<li class="chapter" data-level="5.5" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#space-in-environmental-data"><i class="fa fa-check"></i><b>5.5</b> Space in Environmental Data</a></li>
<li class="chapter" data-level="5.6" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#getting-back-to-distance-matrices"><i class="fa fa-check"></i><b>5.6</b> Getting Back to Distance Matrices</a></li>
<li class="chapter" data-level="5.7" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#meuse-river"><i class="fa fa-check"></i><b>5.7</b> Meuse River</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#using-tmap"><i class="fa fa-check"></i><b>5.7.1</b> Using tmap</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#spatial-autocorrelation-1"><i class="fa fa-check"></i><b>5.8</b> Spatial Autocorrelation</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#variograms"><i class="fa fa-check"></i><b>5.8.1</b> Variograms</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#morans-i"><i class="fa fa-check"></i><b>5.9</b> Moran’s I</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#weights"><i class="fa fa-check"></i><b>5.9.1</b> Weights?</a></li>
<li class="chapter" data-level="5.9.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#library-spdep"><i class="fa fa-check"></i><b>5.9.2</b> Library <code>spdep</code></a></li>
<li class="chapter" data-level="5.9.3" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#library-ncf"><i class="fa fa-check"></i><b>5.9.3</b> Library <code>ncf</code></a></li>
<li class="chapter" data-level="5.9.4" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#discrete-correlogram"><i class="fa fa-check"></i><b>5.9.4</b> Discrete correlogram</a></li>
<li class="chapter" data-level="5.9.5" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#looking-at-distances"><i class="fa fa-check"></i><b>5.9.5</b> Looking at distances</a></li>
<li class="chapter" data-level="5.9.6" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#rolling-your-own-plot"><i class="fa fa-check"></i><b>5.9.6</b> Rolling your own plot</a></li>
<li class="chapter" data-level="5.9.7" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#continuous-correlogram"><i class="fa fa-check"></i><b>5.9.7</b> Continuous correlogram</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#correlograms-on-simulated-data"><i class="fa fa-check"></i><b>5.10</b> Correlograms on simulated data</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#uniform-bumps"><i class="fa fa-check"></i><b>5.10.1</b> Uniform bumps</a></li>
<li class="chapter" data-level="5.10.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#random-bumps"><i class="fa fa-check"></i><b>5.10.2</b> Random bumps</a></li>
<li class="chapter" data-level="5.10.3" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#gradient"><i class="fa fa-check"></i><b>5.10.3</b> Gradient</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#your-work-3"><i class="fa fa-check"></i><b>5.11</b> Your Work</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#interpret"><i class="fa fa-check"></i><b>5.11.1</b> Interpret</a></li>
<li class="chapter" data-level="5.11.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#directional-variograms"><i class="fa fa-check"></i><b>5.11.2</b> Directional Variograms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html"><i class="fa fa-check"></i><b>6</b> Deterministic Interpolation: Inverse Distance Weighting</a>
<ul>
<li class="chapter" data-level="6.1" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#reading-2"><i class="fa fa-check"></i><b>6.1</b> Reading</a></li>
<li class="chapter" data-level="6.2" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#big-idea-4"><i class="fa fa-check"></i><b>6.2</b> Big Idea</a></li>
<li class="chapter" data-level="6.3" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#packages-3"><i class="fa fa-check"></i><b>6.3</b> Packages</a></li>
<li class="chapter" data-level="6.4" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#geostats"><i class="fa fa-check"></i><b>6.4</b> Geostats</a></li>
<li class="chapter" data-level="6.5" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#theory"><i class="fa fa-check"></i><b>6.5</b> Theory</a></li>
<li class="chapter" data-level="6.6" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#toy-example"><i class="fa fa-check"></i><b>6.6</b> Toy example</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#data-1"><i class="fa fa-check"></i><b>6.6.1</b> Data</a></li>
<li class="chapter" data-level="6.6.2" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#idw"><i class="fa fa-check"></i><b>6.6.2</b> IDW</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#application"><i class="fa fa-check"></i><b>6.7</b> Application</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#data-2"><i class="fa fa-check"></i><b>6.7.1</b> Data</a></li>
<li class="chapter" data-level="6.7.2" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#idw-1"><i class="fa fa-check"></i><b>6.7.2</b> IDW</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#skill"><i class="fa fa-check"></i><b>6.8</b> Skill</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#aside-rmse-null-model"><i class="fa fa-check"></i><b>6.8.1</b> Aside: RMSE NULL Model</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#how-can-we-improve-this-model"><i class="fa fa-check"></i><b>6.9</b> How can we improve this model?</a></li>
<li class="chapter" data-level="6.10" data-path="deterministic-interpolation-inverse-distance-weighting.html"><a href="deterministic-interpolation-inverse-distance-weighting.html#your-work-4"><i class="fa fa-check"></i><b>6.10</b> Your Work</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html"><i class="fa fa-check"></i><b>7</b> Deterministic Interpolation: Thin-Plate Splines</a>
<ul>
<li class="chapter" data-level="7.1" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#reading-3"><i class="fa fa-check"></i><b>7.1</b> Reading</a></li>
<li class="chapter" data-level="7.2" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#packages-4"><i class="fa fa-check"></i><b>7.2</b> Packages</a></li>
<li class="chapter" data-level="7.3" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#radial-bias-functions-and-tps"><i class="fa fa-check"></i><b>7.3</b> Radial Bias Functions and TPS</a></li>
<li class="chapter" data-level="7.4" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#application-1"><i class="fa fa-check"></i><b>7.4</b> Application</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#data-3"><i class="fa fa-check"></i><b>7.4.1</b> Data</a></li>
<li class="chapter" data-level="7.4.2" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#tps"><i class="fa fa-check"></i><b>7.4.2</b> TPS</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#skill-1"><i class="fa fa-check"></i><b>7.5</b> Skill</a></li>
<li class="chapter" data-level="7.6" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#is-this-an-improvement"><i class="fa fa-check"></i><b>7.6</b> Is this an Improvement?</a></li>
<li class="chapter" data-level="7.7" data-path="deterministic-interpolation-thin-plate-splines.html"><a href="deterministic-interpolation-thin-plate-splines.html#your-work-5"><i class="fa fa-check"></i><b>7.7</b> Your work</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html"><i class="fa fa-check"></i><b>8</b> Probabilistic Interpolation: Kriging</a>
<ul>
<li class="chapter" data-level="8.1" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#reading-4"><i class="fa fa-check"></i><b>8.1</b> Reading</a></li>
<li class="chapter" data-level="8.2" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#big-idea-5"><i class="fa fa-check"></i><b>8.2</b> Big Idea</a></li>
<li class="chapter" data-level="8.3" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#packages-5"><i class="fa fa-check"></i><b>8.3</b> Packages</a></li>
<li class="chapter" data-level="8.4" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#some-kriging-theory"><i class="fa fa-check"></i><b>8.4</b> Some Kriging Theory</a></li>
<li class="chapter" data-level="8.5" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#variogram-redux"><i class="fa fa-check"></i><b>8.5</b> Variogram Redux</a></li>
<li class="chapter" data-level="8.6" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#variogram-model"><i class="fa fa-check"></i><b>8.6</b> Variogram Model</a></li>
<li class="chapter" data-level="8.7" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#putting-it-together"><i class="fa fa-check"></i><b>8.7</b> Putting it Together</a></li>
<li class="chapter" data-level="8.8" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#toy-example-1"><i class="fa fa-check"></i><b>8.8</b> Toy Example</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#data-4"><i class="fa fa-check"></i><b>8.8.1</b> Data</a></li>
<li class="chapter" data-level="8.8.2" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#interpolate-with-kriging"><i class="fa fa-check"></i><b>8.8.2</b> Interpolate with Kriging</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#application-kriging-a-lead-surface"><i class="fa fa-check"></i><b>8.9</b> Application: Kriging a Lead Surface</a></li>
<li class="chapter" data-level="8.10" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#uncertainty"><i class="fa fa-check"></i><b>8.10</b> Uncertainty</a></li>
<li class="chapter" data-level="8.11" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#other-variogram-models"><i class="fa fa-check"></i><b>8.11</b> Other Variogram Models</a></li>
<li class="chapter" data-level="8.12" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#other-types-of-kriging"><i class="fa fa-check"></i><b>8.12</b> Other Types of Kriging</a></li>
<li class="chapter" data-level="8.13" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#cross-validation"><i class="fa fa-check"></i><b>8.13</b> Cross Validation</a></li>
<li class="chapter" data-level="8.14" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#your-work-6"><i class="fa fa-check"></i><b>8.14</b> Your Work</a></li>
<li class="chapter" data-level="8.15" data-path="probabilistic-interpolation-kriging.html"><a href="probabilistic-interpolation-kriging.html#postscript-automap"><i class="fa fa-check"></i><b>8.15</b> Postscript: Automap</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html"><i class="fa fa-check"></i><b>9</b> Probabilistic Interpolation: Regression Kriging</a>
<ul>
<li class="chapter" data-level="9.1" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#big-idea-6"><i class="fa fa-check"></i><b>9.1</b> Big Idea</a></li>
<li class="chapter" data-level="9.2" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#reading-5"><i class="fa fa-check"></i><b>9.2</b> Reading</a></li>
<li class="chapter" data-level="9.3" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#packages-6"><i class="fa fa-check"></i><b>9.3</b> Packages</a></li>
<li class="chapter" data-level="9.4" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#overview-of-rk"><i class="fa fa-check"></i><b>9.4</b> Overview of RK</a></li>
<li class="chapter" data-level="9.5" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#prediction-review-ols-regression-with-new-data"><i class="fa fa-check"></i><b>9.5</b> Prediction Review: OLS Regression with New Data</a></li>
<li class="chapter" data-level="9.6" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#back-to-the-netherlands"><i class="fa fa-check"></i><b>9.6</b> Back to the Netherlands</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#the-data-1"><i class="fa fa-check"></i><b>9.6.1</b> The Data</a></li>
<li class="chapter" data-level="9.6.2" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#make-data-as-sf-and-clean-it-up"><i class="fa fa-check"></i><b>9.6.2</b> Make data as <code>sf</code> and clean it up</a></li>
<li class="chapter" data-level="9.6.3" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#ols"><i class="fa fa-check"></i><b>9.6.3</b> OLS</a></li>
<li class="chapter" data-level="9.6.4" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#rk-application"><i class="fa fa-check"></i><b>9.6.4</b> RK Application</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="probabilistic-interpolation-regression-kriging.html"><a href="probabilistic-interpolation-regression-kriging.html#your-work-7"><i class="fa fa-check"></i><b>9.7</b> Your Work</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html"><i class="fa fa-check"></i>Aside: Kriging Variance By Hand</a>
<ul>
<li class="chapter" data-level="9.8" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#whats-going-on-here"><i class="fa fa-check"></i><b>9.8</b> What’s Going On Here</a></li>
<li class="chapter" data-level="9.9" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#the-setup"><i class="fa fa-check"></i><b>9.9</b> The Setup</a></li>
<li class="chapter" data-level="9.10" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#the-covariance-functions"><i class="fa fa-check"></i><b>9.10</b> The Covariance Functions</a></li>
<li class="chapter" data-level="9.11" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#building-the-covariance-matrix-and-vector"><i class="fa fa-check"></i><b>9.11</b> Building the Covariance Matrix and Vector</a></li>
<li class="chapter" data-level="9.12" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#simple-kriging"><i class="fa fa-check"></i><b>9.12</b> Simple Kriging</a></li>
<li class="chapter" data-level="9.13" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#ordinary-kriging"><i class="fa fa-check"></i><b>9.13</b> Ordinary Kriging</a></li>
<li class="chapter" data-level="9.14" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#checking-against-gstat"><i class="fa fa-check"></i><b>9.14</b> Checking Against gstat</a></li>
<li class="chapter" data-level="9.15" data-path="aside-kriging-variance-by-hand.html"><a href="aside-kriging-variance-by-hand.html#the-results"><i class="fa fa-check"></i><b>9.15</b> The Results</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html"><i class="fa fa-check"></i><b>10</b> Regression: GLS with Autocorrelated Residuals</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#big-idea-7"><i class="fa fa-check"></i><b>10.1</b> Big Idea</a></li>
<li class="chapter" data-level="10.2" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#reading-6"><i class="fa fa-check"></i><b>10.2</b> Reading</a></li>
<li class="chapter" data-level="10.3" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#packages-7"><i class="fa fa-check"></i><b>10.3</b> Packages</a></li>
<li class="chapter" data-level="10.4" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#regression"><i class="fa fa-check"></i><b>10.4</b> Regression</a></li>
<li class="chapter" data-level="10.5" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#gls-and-ols"><i class="fa fa-check"></i><b>10.5</b> GLS and OLS</a></li>
<li class="chapter" data-level="10.6" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#toy-example-2"><i class="fa fa-check"></i><b>10.6</b> Toy Example</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#data-5"><i class="fa fa-check"></i><b>10.6.1</b> Data</a></li>
<li class="chapter" data-level="10.6.2" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#analysis"><i class="fa fa-check"></i><b>10.6.2</b> Analysis</a></li>
<li class="chapter" data-level="10.6.3" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#interpretation"><i class="fa fa-check"></i><b>10.6.3</b> Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="regression-gls-with-autocorrelated-residuals.html"><a href="regression-gls-with-autocorrelated-residuals.html#your-work-8"><i class="fa fa-check"></i><b>10.7</b> Your work</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html"><i class="fa fa-check"></i>Aside: OLS via Algebra and Matrices</a>
<ul>
<li class="chapter" data-level="10.8" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html#why-are-we-doing-this"><i class="fa fa-check"></i><b>10.8</b> Why Are We Doing This?</a></li>
<li class="chapter" data-level="10.9" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html#the-algebraic-approach"><i class="fa fa-check"></i><b>10.9</b> The Algebraic Approach</a></li>
<li class="chapter" data-level="10.10" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html#the-matrix-approach"><i class="fa fa-check"></i><b>10.10</b> The Matrix Approach</a></li>
<li class="chapter" data-level="10.11" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html#implementation-in-r"><i class="fa fa-check"></i><b>10.11</b> Implementation in R</a></li>
<li class="chapter" data-level="10.12" data-path="aside-ols-via-algebra-and-matrices.html"><a href="aside-ols-via-algebra-and-matrices.html#why-this-matters-for-gls"><i class="fa fa-check"></i><b>10.12</b> Why This Matters for GLS</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>11</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Analysis for Environmental Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="probabilistic-interpolation-regression-kriging" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">9</span> Probabilistic Interpolation: Regression Kriging<a href="probabilistic-interpolation-regression-kriging.html#probabilistic-interpolation-regression-kriging" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="big-idea-6" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Big Idea<a href="probabilistic-interpolation-regression-kriging.html#big-idea-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With kriging we used limited spatial data to make predictions (interpolation) over larger areas. Regression kriging is going to use the same theory but incorporate ancillary data to make better predictions.</p>
</div>
<div id="reading-5" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Reading<a href="probabilistic-interpolation-regression-kriging.html#reading-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Meng et al. (2013) provide a (mostly) readable description of regression kriging and compare it to the kind of interpolation approaches we’ve looked at already. Give it a heavy skim.</p>
<p>Meng et al. (2013) Assessment of regression kriging for spatial interpolation – comparisons of seven GIS interpolation methods. Cartography and Geographic Information Science, 40:1, 28-39, doi:
10.1080/15230406.2013.762138.</p>
</div>
<div id="packages-6" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Packages<a href="probabilistic-interpolation-regression-kriging.html#packages-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>gstat</code> package is your friend. But we will need some of our recent collaborators as well including <code>terra</code> and `tidyterra’.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="probabilistic-interpolation-regression-kriging.html#cb278-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb278-2"><a href="probabilistic-interpolation-regression-kriging.html#cb278-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb278-3"><a href="probabilistic-interpolation-regression-kriging.html#cb278-3" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb278-4"><a href="probabilistic-interpolation-regression-kriging.html#cb278-4" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span>
<span id="cb278-5"><a href="probabilistic-interpolation-regression-kriging.html#cb278-5" tabindex="-1"></a><span class="fu">library</span>(gstat)</span></code></pre></div>
</div>
<div id="overview-of-rk" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Overview of RK<a href="probabilistic-interpolation-regression-kriging.html#overview-of-rk" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Regression kriging (RK) is a spatial interpolation technique (like IDW, thin-plate splines, and kriging) that allows for estimation of a variable across a spatial domain. Like the name suggests, RK combines regression and kriging. It is a probabilistic method and produces a variance surface like kriging.</p>
<p>RK uses a regression of the dependent variable (<span class="math inline">\(y\)</span>) on predictor variables (<span class="math inline">\(x_1\)</span>,<span class="math inline">\(x_2\)</span>, etc.) with standard kriging of the errors on the regression. By fitting a variogram to the residuals of the model, predictors influence the kriging weights (recall <span class="math inline">\(\lambda\)</span> from the kriging module?). The advantage of RK over either kriging or regression is that it combines the use of spatial structure for prediction (as kriging does) with the addition of ancillary variables (like regression does). In other words, RK exploits the spatial correlation between variables for making predictions.</p>
<p>RK is used more and more commonly as cheap and powerful covariates can be derived from remote sensing and GIS data. I’ll give some examples in the video.</p>
</div>
<div id="prediction-review-ols-regression-with-new-data" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Prediction Review: OLS Regression with New Data<a href="probabilistic-interpolation-regression-kriging.html#prediction-review-ols-regression-with-new-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is likely serious review for all of you so roll your eyes as needed. But I just want to be sure we are on the same page. I want to make sure you are hip to the idea of passing new data (e.g., into a <code>predict</code> function) for extending a model (e.g., <code>lm</code>) to new data. We’ve done this already a few times, but it never hurts to get it again.</p>
<p>Here we create a <code>data.frame</code> called <code>originalDat</code> with three variables: <code>x1</code> and <code>x2</code> are <code>n</code> draws from a normal distribution (<span class="math inline">\(N(0,1)\)</span>) and <code>y</code> is a function of <code>x1</code>and <code>x2</code> following a linear model with coefficients <code>b0</code>, <code>b1</code>, and <code>b2</code> plus some more noise (<code>epsilon</code>) (<span class="math inline">\(N(0,2)\)</span>).</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="probabilistic-interpolation-regression-kriging.html#cb279-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb279-2"><a href="probabilistic-interpolation-regression-kriging.html#cb279-2" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb279-3"><a href="probabilistic-interpolation-regression-kriging.html#cb279-3" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fl">0.6</span></span>
<span id="cb279-4"><a href="probabilistic-interpolation-regression-kriging.html#cb279-4" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb279-5"><a href="probabilistic-interpolation-regression-kriging.html#cb279-5" tabindex="-1"></a>originalDat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1=</span><span class="fu">rnorm</span>(n), <span class="at">x2=</span><span class="fu">rnorm</span>(n), <span class="at">epsilon =</span> <span class="fu">rnorm</span>(n,<span class="at">sd =</span> <span class="dv">2</span>))</span>
<span id="cb279-6"><a href="probabilistic-interpolation-regression-kriging.html#cb279-6" tabindex="-1"></a>originalDat<span class="sc">$</span>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> originalDat<span class="sc">$</span>x1 <span class="sc">+</span> b2 <span class="sc">*</span> originalDat<span class="sc">$</span>x2 <span class="sc">+</span> originalDat<span class="sc">$</span>epsilon</span></code></pre></div>
<p>We then fit a linear model (OLS) with <code>lm</code>:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="probabilistic-interpolation-regression-kriging.html#cb280-1" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y<span class="sc">~</span>x1 <span class="sc">+</span> x2,<span class="at">data =</span> originalDat)</span>
<span id="cb280-2"><a href="probabilistic-interpolation-regression-kriging.html#cb280-2" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2, data = originalDat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.9446 -1.4464 -0.3522  1.2004  4.5087 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.5699     0.2841  12.567  &lt; 2e-16 ***
## x1            0.4794     0.2650   1.809   0.0768 .  
## x2            2.8109     0.3556   7.904 3.55e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.968 on 47 degrees of freedom
## Multiple R-squared:  0.5788, Adjusted R-squared:  0.5609 
## F-statistic: 32.29 on 2 and 47 DF,  p-value: 1.497e-09</code></pre>
<p>OK. We have one definitely helpful predictor, and one borderline predictor. Now let’s say we want to extend that model to predict a new data set. The object <code>lm1</code> is class <code>lm</code> and most every model class has a <code>predict</code> function, or a <code>newdata</code> argument to the original function, that allows you feed it new data. So let’s imagine we have a new data set with <code>x1</code> and <code>x2</code> but no <code>y</code>.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="probabilistic-interpolation-regression-kriging.html#cb282-1" tabindex="-1"></a>newDat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1=</span><span class="fu">rnorm</span>(n),<span class="at">x2=</span><span class="fu">rnorm</span>(n))</span>
<span id="cb282-2"><a href="probabilistic-interpolation-regression-kriging.html#cb282-2" tabindex="-1"></a><span class="fu">head</span>(newDat)</span></code></pre></div>
<pre><code>##           x1         x2
## 1 -0.9107046  0.1053673
## 2 -1.9548906 -0.2345276
## 3 -0.5561183  0.1375432
## 4 -0.7254766  0.3132995
## 5 -0.5021313  1.1485350
## 6  0.1749991  0.8071396</code></pre>
<p>We can use <code>predict.lm</code> (we just need to type <code>predict</code> since the object we are feeding is class <code>lm</code>, R knows to use <code>predict.lm</code>) to model new estimates of <code>y</code> by pointing to <code>newDat</code> using the <code>newdata</code> argument. Note that I’m sticking the predicted values right into a new column <code>yhat</code>. Why the hat? Because it’s an estimate.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="probabilistic-interpolation-regression-kriging.html#cb284-1" tabindex="-1"></a>newDat<span class="sc">$</span>yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object =</span> lm1,<span class="at">newdata =</span> newDat)</span>
<span id="cb284-2"><a href="probabilistic-interpolation-regression-kriging.html#cb284-2" tabindex="-1"></a><span class="fu">head</span>(newDat)</span></code></pre></div>
<pre><code>##           x1         x2     yhat
## 1 -0.9107046  0.1053673 3.429497
## 2 -1.9548906 -0.2345276 1.973452
## 3 -0.5561183  0.1375432 3.689944
## 4 -0.7254766  0.3132995 4.102786
## 5 -0.5021313  1.1485350 6.557656
## 6  0.1749991  0.8071396 5.922660</code></pre>
<p>If we call <code>predict</code> without new data, the fits from the original model are returned. In the above <code>predict(lm1)</code>, <code>fitted(lm1)</code>, and <code>lm1$fitted.values</code> all do the same thing.</p>
<p>I know that most of you are familiar with this. I just wanted to spell it all out.</p>
</div>
<div id="back-to-the-netherlands" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Back to the Netherlands<a href="probabilistic-interpolation-regression-kriging.html#back-to-the-netherlands" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s look at a real-world example of RK using, you guessed it, the Meuse River data. I’m pretty sick of these data but they are familiar to us. We’ve used the data in <code>meuse.all</code> quite a bit and we’ve used <code>meuse.grid</code> as an empty grid to interpolate into. But <code>meuse.grid</code> has other data in it that we can use in a regression kriging approach.</p>
<div id="the-data-1" class="section level3 hasAnchor" number="9.6.1">
<h3><span class="header-section-number">9.6.1</span> The Data<a href="probabilistic-interpolation-regression-kriging.html#the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="probabilistic-interpolation-regression-kriging.html#cb286-1" tabindex="-1"></a><span class="fu">data</span>(meuse.all)</span>
<span id="cb286-2"><a href="probabilistic-interpolation-regression-kriging.html#cb286-2" tabindex="-1"></a><span class="fu">str</span>(meuse.all)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    164 obs. of  17 variables:
##  $ sample     : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ x          : num  181072 181025 181165 181298 181307 ...
##  $ y          : num  333611 333558 333537 333484 333330 ...
##  $ cadmium    : num  11.7 8.6 6.5 2.6 2.8 3 3.2 2.8 2.4 1.6 ...
##  $ copper     : num  85 81 68 81 48 61 31 29 37 24 ...
##  $ lead       : num  299 277 199 116 117 137 132 150 133 80 ...
##  $ zinc       : num  1022 1141 640 257 269 ...
##  $ elev       : num  7.91 6.98 7.8 7.66 7.48 ...
##  $ dist.m     : num  50 30 150 270 380 470 240 120 240 420 ...
##  $ om         : num  13.6 14 13 8 8.7 7.8 9.2 9.5 10.6 6.3 ...
##  $ ffreq      : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ soil       : num  1 1 1 2 2 2 2 1 1 2 ...
##  $ lime       : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ landuse    : Factor w/ 16 levels &quot;Aa&quot;,&quot;Ab&quot;,&quot;Ag&quot;,..: 4 4 4 11 4 11 4 2 2 16 ...
##  $ in.pit     : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
##  $ in.meuse155: logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
##  $ in.BMcD    : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...</code></pre>
<p>We know all too well by now that <code>meuse.all</code> is a <code>data.frame</code> with 164 point measurements of 17 variables.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="probabilistic-interpolation-regression-kriging.html#cb288-1" tabindex="-1"></a>meuse.grid <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/meuse.grid.Rds&quot;</span>)</span>
<span id="cb288-2"><a href="probabilistic-interpolation-regression-kriging.html#cb288-2" tabindex="-1"></a><span class="fu">str</span>(meuse.grid)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    3103 obs. of  7 variables:
##  $ x     : num  181180 181140 181180 181220 181100 ...
##  $ y     : num  333740 333700 333700 333700 333660 ...
##  $ part.a: num  1 1 1 1 1 1 1 1 1 1 ...
##  $ part.b: num  0 0 0 0 0 0 0 0 0 0 ...
##  $ dist  : num  0 0 0.0122 0.0435 0 ...
##  $ soil  : Factor w/ 3 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ ffreq : Factor w/ 3 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>And, we know all too well by now that <code>meuse.grid</code> is a <code>data.frame</code> with 3103 points on a grid and 7 variables.</p>
<p>However, we have three variables from <code>meuse.all</code> that overlap in <code>meuse.grid</code> and we haven’t used those much (or at all) in this class yet. Thus, if we create a model from <code>meuse.all</code> that includes <code>dist</code>, <code>soil</code>, or <code>ffreq</code> as predictors we could predict over <code>meuse.grid</code> without doing IDW or kriging. Those variables held in common between <code>meuse.all</code> and <code>meuse.grid</code> are, by the way, the distance to the river (normalized from 0 to 1), soil type (three classes), and the flooding frequency class (also three classes). See <code>?meuse.all</code> for details on the variables.</p>
<p>Don’t worry, we will skip cadmium, zinc, and lead and work with modeling <code>om</code> which is percent organic matter in the soil. We will model <code>om</code> as a function of <code>dist</code> and <code>soil</code> and predict it over the entire study site. We will do this naively with ordinary least squares regression (OLS) and then again with RK.</p>
</div>
<div id="make-data-as-sf-and-clean-it-up" class="section level3 hasAnchor" number="9.6.2">
<h3><span class="header-section-number">9.6.2</span> Make data as <code>sf</code> and clean it up<a href="probabilistic-interpolation-regression-kriging.html#make-data-as-sf-and-clean-it-up" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Fist we will make both data sets in <code>sf</code> objects.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="probabilistic-interpolation-regression-kriging.html#cb290-1" tabindex="-1"></a>meusePoints_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.all,<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;x&quot;</span>,<span class="st">&quot;y&quot;</span>), <span class="at">crs=</span><span class="dv">28992</span>)</span>
<span id="cb290-2"><a href="probabilistic-interpolation-regression-kriging.html#cb290-2" tabindex="-1"></a>meuseGrid_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(meuse.grid,<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;x&quot;</span>,<span class="st">&quot;y&quot;</span>), <span class="at">crs=</span><span class="dv">28992</span>)</span>
<span id="cb290-3"><a href="probabilistic-interpolation-regression-kriging.html#cb290-3" tabindex="-1"></a>meusePoints_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 164 features and 15 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611
## Projected CRS: Amersfoort / RD New
## First 10 features:
##    sample cadmium copper lead zinc  elev dist.m   om ffreq soil lime landuse
## 1       1    11.7     85  299 1022 7.909     50 13.6     1    1    1      Ah
## 2       2     8.6     81  277 1141 6.983     30 14.0     1    1    1      Ah
## 3       3     6.5     68  199  640 7.800    150 13.0     1    1    1      Ah
## 4       4     2.6     81  116  257 7.655    270  8.0     1    2    0      Ga
## 5       5     2.8     48  117  269 7.480    380  8.7     1    2    0      Ah
## 6       6     3.0     61  137  281 7.791    470  7.8     1    2    0      Ga
## 7       7     3.2     31  132  346 8.217    240  9.2     1    2    0      Ah
## 8       8     2.8     29  150  406 8.490    120  9.5     1    1    0      Ab
## 9       9     2.4     37  133  347 8.668    240 10.6     1    1    0      Ab
## 10     10     1.6     24   80  183 9.049    420  6.3     1    2    0       W
##    in.pit in.meuse155 in.BMcD              geometry
## 1   FALSE        TRUE   FALSE POINT (181072 333611)
## 2   FALSE        TRUE   FALSE POINT (181025 333558)
## 3   FALSE        TRUE   FALSE POINT (181165 333537)
## 4   FALSE        TRUE   FALSE POINT (181298 333484)
## 5   FALSE        TRUE   FALSE POINT (181307 333330)
## 6   FALSE        TRUE   FALSE POINT (181390 333260)
## 7   FALSE        TRUE   FALSE POINT (181165 333370)
## 8   FALSE        TRUE   FALSE POINT (181027 333363)
## 9   FALSE        TRUE   FALSE POINT (181060 333231)
## 10  FALSE        TRUE   FALSE POINT (181232 333168)</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="probabilistic-interpolation-regression-kriging.html#cb292-1" tabindex="-1"></a>meuseGrid_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 3103 features and 5 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740
## Projected CRS: Amersfoort / RD New
## First 10 features:
##    part.a part.b       dist soil ffreq              geometry
## 1       1      0 0.00000000    1     1 POINT (181180 333740)
## 2       1      0 0.00000000    1     1 POINT (181140 333700)
## 3       1      0 0.01222430    1     1 POINT (181180 333700)
## 4       1      0 0.04346780    1     1 POINT (181220 333700)
## 5       1      0 0.00000000    1     1 POINT (181100 333660)
## 6       1      0 0.01222430    1     1 POINT (181140 333660)
## 7       1      0 0.03733950    1     1 POINT (181180 333660)
## 8       1      0 0.05936620    1     1 POINT (181220 333660)
## 9       1      0 0.00135803    1     1 POINT (181060 333620)
## 10      1      0 0.01222430    1     1 POINT (181100 333620)</code></pre>
<p>One thing to note here is that the <code>dist.m</code> column in <code>meusePoints_sf</code> is the distance to the river in meters while <code>meuseGrid_sf</code> has distance to the river in relative units (scaled zero to one). To make life easier we will add the relative distances to the point data unsing the <code>dist</code> values from <code>meuseGrid_sf</code>.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="probabilistic-interpolation-regression-kriging.html#cb294-1" tabindex="-1"></a><span class="co"># get the relative distance from meuseGrid_sf and add it to meusePoints_sf</span></span>
<span id="cb294-2"><a href="probabilistic-interpolation-regression-kriging.html#cb294-2" tabindex="-1"></a>meuseGrid_dist_sf <span class="ot">&lt;-</span> meuseGrid_sf <span class="sc">%&gt;%</span> <span class="fu">select</span>(dist)</span>
<span id="cb294-3"><a href="probabilistic-interpolation-regression-kriging.html#cb294-3" tabindex="-1"></a><span class="co"># join the two objects by the nearest point</span></span>
<span id="cb294-4"><a href="probabilistic-interpolation-regression-kriging.html#cb294-4" tabindex="-1"></a>meusePoints_sf <span class="ot">&lt;-</span> <span class="fu">st_join</span>(meusePoints_sf,meuseGrid_dist_sf, <span class="at">join =</span> st_nearest_feature)</span>
<span id="cb294-5"><a href="probabilistic-interpolation-regression-kriging.html#cb294-5" tabindex="-1"></a><span class="co"># note that we now have relative dist for each point now in the column `dist`</span></span>
<span id="cb294-6"><a href="probabilistic-interpolation-regression-kriging.html#cb294-6" tabindex="-1"></a>meusePoints_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 164 features and 16 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611
## Projected CRS: Amersfoort / RD New
## First 10 features:
##    sample cadmium copper lead zinc  elev dist.m   om ffreq soil lime landuse
## 1       1    11.7     85  299 1022 7.909     50 13.6     1    1    1      Ah
## 2       2     8.6     81  277 1141 6.983     30 14.0     1    1    1      Ah
## 3       3     6.5     68  199  640 7.800    150 13.0     1    1    1      Ah
## 4       4     2.6     81  116  257 7.655    270  8.0     1    2    0      Ga
## 5       5     2.8     48  117  269 7.480    380  8.7     1    2    0      Ah
## 6       6     3.0     61  137  281 7.791    470  7.8     1    2    0      Ga
## 7       7     3.2     31  132  346 8.217    240  9.2     1    2    0      Ah
## 8       8     2.8     29  150  406 8.490    120  9.5     1    1    0      Ab
## 9       9     2.4     37  133  347 8.668    240 10.6     1    1    0      Ab
## 10     10     1.6     24   80  183 9.049    420  6.3     1    2    0       W
##    in.pit in.meuse155 in.BMcD       dist              geometry
## 1   FALSE        TRUE   FALSE 0.00135803 POINT (181072 333611)
## 2   FALSE        TRUE   FALSE 0.01222430 POINT (181025 333558)
## 3   FALSE        TRUE   FALSE 0.10302900 POINT (181165 333537)
## 4   FALSE        TRUE   FALSE 0.19009400 POINT (181298 333484)
## 5   FALSE        TRUE   FALSE 0.27709000 POINT (181307 333330)
## 6   FALSE        TRUE   FALSE 0.36406700 POINT (181390 333260)
## 7   FALSE        TRUE   FALSE 0.19009400 POINT (181165 333370)
## 8   FALSE        TRUE   FALSE 0.09215160 POINT (181027 333363)
## 9   FALSE        TRUE   FALSE 0.18461400 POINT (181060 333231)
## 10  FALSE        TRUE   FALSE 0.30970200 POINT (181232 333168)</code></pre>
<p>We will go a step further and use the square root of the distance to the river as a predictor. This just helps us get a little more leverage on very short distances by stretching out the scale.</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="probabilistic-interpolation-regression-kriging.html#cb296-1" tabindex="-1"></a>meusePoints_sf <span class="ot">&lt;-</span> meusePoints_sf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sqrt_dist =</span> <span class="fu">sqrt</span>(dist))</span>
<span id="cb296-2"><a href="probabilistic-interpolation-regression-kriging.html#cb296-2" tabindex="-1"></a>meuseGrid_sf <span class="ot">&lt;-</span> meuseGrid_sf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sqrt_dist =</span> <span class="fu">sqrt</span>(dist))</span></code></pre></div>
<p>Next, the column <code>om</code> in <code>meusePoints_sf</code> has two missing data points (<code>NA</code>) in it. I’m going to toss those rows to make things easier. Note the new number of rows in <code>meusePoints_sf</code> after you run this.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="probabilistic-interpolation-regression-kriging.html#cb297-1" tabindex="-1"></a>meusePoints_sf <span class="ot">&lt;-</span> meusePoints_sf <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(om)</span></code></pre></div>
<p>And finally, we are going to be using the soil type as a predictor. That is a categorical variable so we need to change it to be a <code>factor</code>.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="probabilistic-interpolation-regression-kriging.html#cb298-1" tabindex="-1"></a>meusePoints_sf <span class="ot">&lt;-</span> meusePoints_sf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">soil =</span> <span class="fu">factor</span>(soil))</span>
<span id="cb298-2"><a href="probabilistic-interpolation-regression-kriging.html#cb298-2" tabindex="-1"></a>meuseGrid_sf <span class="ot">&lt;-</span> meuseGrid_sf <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">soil =</span> <span class="fu">factor</span>(soil))</span></code></pre></div>
</div>
<div id="ols" class="section level3 hasAnchor" number="9.6.3">
<h3><span class="header-section-number">9.6.3</span> OLS<a href="probabilistic-interpolation-regression-kriging.html#ols" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will make a simple model of organic matter (<span class="math inline">\(y\)</span>) as a function of the square root of the distance to the river (<span class="math inline">\(x_1\)</span>) and soil type (<span class="math inline">\(x_2\)</span>): <span class="math inline">\(y=\beta_0 + \beta_1x_1+\beta_2x_2\)</span>. The parameters (<span class="math inline">\(\beta_{0,1,2}\)</span>) will be estimated with OLS.
Here is the OLS model:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="probabilistic-interpolation-regression-kriging.html#cb299-1" tabindex="-1"></a>om_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(om<span class="sc">~</span>sqrt_dist<span class="sc">+</span>soil, <span class="at">data=</span>meusePoints_sf)</span>
<span id="cb299-2"><a href="probabilistic-interpolation-regression-kriging.html#cb299-2" tabindex="-1"></a><span class="fu">summary</span>(om_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = om ~ sqrt_dist + soil, data = meusePoints_sf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.8478 -1.4629 -0.1575  1.4344  7.3786 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.6894     0.4418  26.460  &lt; 2e-16 ***
## sqrt_dist    -8.9179     1.0902  -8.180 8.79e-14 ***
## soil2        -1.7178     0.5047  -3.403 0.000843 ***
## soil3         0.7120     0.8628   0.825 0.410449    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.473 on 158 degrees of freedom
## Multiple R-squared:  0.4926, Adjusted R-squared:  0.4829 
## F-statistic: 51.12 on 3 and 158 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="probabilistic-interpolation-regression-kriging.html#cb301-1" tabindex="-1"></a><span class="fu">anova</span>(om_lm)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: om
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## sqrt_dist   1 833.08  833.08 136.197 &lt; 2.2e-16 ***
## soil        2 105.07   52.54   8.589 0.0002877 ***
## Residuals 158 966.45    6.12                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In our model, we see that both distance and soil types are good predictors of organic matter percent. Now, this might or might not be a good model. After you learn about the pitfalls of using OLS with spatial data you’ll be appalled that I’m running this model and not checking for spatial autocorrelation in the residuals or doing any other regression diagnostics. But suppress your horror for now. Because all I want to do here is show how I could (if I wanted to live in a state of ignorant bliss) predict this model across the landscape.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="probabilistic-interpolation-regression-kriging.html#cb303-1" tabindex="-1"></a>meuseGrid_sf<span class="sc">$</span>omHat <span class="ot">&lt;-</span> <span class="fu">predict</span>(om_lm, <span class="at">newdata=</span>meuseGrid_sf)</span>
<span id="cb303-2"><a href="probabilistic-interpolation-regression-kriging.html#cb303-2" tabindex="-1"></a></span>
<span id="cb303-3"><a href="probabilistic-interpolation-regression-kriging.html#cb303-3" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_sf</span>(<span class="at">data =</span> meuseGrid_sf,<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">color=</span>omHat))</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-15-1.png" alt="" width="672" /></p>
<p>A few things. One this is a decent prediction. The model relatively skillful (but we should crossvalidate it) but the assumption about independence of the residuals is violated. E.g., Moran’s I on an eight-neighbor object is 0.23 which is significantly greater than zero. More on that in the next set of notes “GLS with Autocorrelated Residuals.” Oh, and that plot above is all points. We can make it a raster. Remember this handy function from the prior weeks that makes a <code>sf</code> point object into a <code>SpatRaster</code>?</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="probabilistic-interpolation-regression-kriging.html#cb304-1" tabindex="-1"></a>sf_2_rast <span class="ot">&lt;-</span><span class="cf">function</span>(sfObject,<span class="at">variable2get =</span> <span class="dv">1</span>){</span>
<span id="cb304-2"><a href="probabilistic-interpolation-regression-kriging.html#cb304-2" tabindex="-1"></a>  <span class="co"># coerce sf to a data.frame</span></span>
<span id="cb304-3"><a href="probabilistic-interpolation-regression-kriging.html#cb304-3" tabindex="-1"></a>  tmp <span class="ot">&lt;-</span> sfObject[,variable2get] <span class="sc">%&gt;%</span> <span class="fu">st_drop_geometry</span>()</span>
<span id="cb304-4"><a href="probabilistic-interpolation-regression-kriging.html#cb304-4" tabindex="-1"></a>  dfObject <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">st_coordinates</span>(sfObject),</span>
<span id="cb304-5"><a href="probabilistic-interpolation-regression-kriging.html#cb304-5" tabindex="-1"></a>                         <span class="at">z=</span>tmp)</span>
<span id="cb304-6"><a href="probabilistic-interpolation-regression-kriging.html#cb304-6" tabindex="-1"></a>  <span class="co"># coerce data.frame to SpatRaster</span></span>
<span id="cb304-7"><a href="probabilistic-interpolation-regression-kriging.html#cb304-7" tabindex="-1"></a>  rastObject <span class="ot">&lt;-</span> <span class="fu">rast</span>(dfObject,<span class="at">crs=</span><span class="fu">crs</span>(sfObject))</span>
<span id="cb304-8"><a href="probabilistic-interpolation-regression-kriging.html#cb304-8" tabindex="-1"></a>  </span>
<span id="cb304-9"><a href="probabilistic-interpolation-regression-kriging.html#cb304-9" tabindex="-1"></a>  <span class="fu">return</span>(rastObject)</span>
<span id="cb304-10"><a href="probabilistic-interpolation-regression-kriging.html#cb304-10" tabindex="-1"></a>}</span>
<span id="cb304-11"><a href="probabilistic-interpolation-regression-kriging.html#cb304-11" tabindex="-1"></a></span>
<span id="cb304-12"><a href="probabilistic-interpolation-regression-kriging.html#cb304-12" tabindex="-1"></a>meuseGrid_rast <span class="ot">&lt;-</span> <span class="fu">sf_2_rast</span>(meuseGrid_sf,<span class="at">variable2get =</span> <span class="st">&quot;omHat&quot;</span>)</span>
<span id="cb304-13"><a href="probabilistic-interpolation-regression-kriging.html#cb304-13" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_spatraster</span>(<span class="at">data =</span> meuseGrid_rast,</span>
<span id="cb304-14"><a href="probabilistic-interpolation-regression-kriging.html#cb304-14" tabindex="-1"></a>                           <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill=</span>omHat)) <span class="sc">+</span></span>
<span id="cb304-15"><a href="probabilistic-interpolation-regression-kriging.html#cb304-15" tabindex="-1"></a>  <span class="fu">scale_fill_terrain_c</span>() <span class="sc">+</span></span>
<span id="cb304-16"><a href="probabilistic-interpolation-regression-kriging.html#cb304-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;omHat&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-17-1.png" alt="" width="672" /></p>
</div>
<div id="rk-application" class="section level3 hasAnchor" number="9.6.4">
<h3><span class="header-section-number">9.6.4</span> RK Application<a href="probabilistic-interpolation-regression-kriging.html#rk-application" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As I imagine you have anticipated, the silliest thing in the model above is that we threw out all of the awesome data we have on spatial structure. All the information on how pairs of samples relate to each other in terms of semivariance has been cast aside. And we know that organic matter is autocorrelated. E.g.,:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="probabilistic-interpolation-regression-kriging.html#cb305-1" tabindex="-1"></a>omVar <span class="ot">&lt;-</span> <span class="fu">variogram</span>(om<span class="sc">~</span><span class="dv">1</span>, meusePoints_sf)</span>
<span id="cb305-2"><a href="probabilistic-interpolation-regression-kriging.html#cb305-2" tabindex="-1"></a><span class="fu">plot</span>(omVar,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">&quot;black&quot;</span>,</span>
<span id="cb305-3"><a href="probabilistic-interpolation-regression-kriging.html#cb305-3" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">&quot;Semivariance (&quot;</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">&quot;)&quot;</span>),</span>
<span id="cb305-4"><a href="probabilistic-interpolation-regression-kriging.html#cb305-4" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Distance (m)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;% Soil Organic Matter&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-18-1.png" alt="" width="672" /></p>
<p>With kriging, we would interpolate a surface based just on a theoretical variogram we would fit to those data. But we have all the data on distance and soil type that we used in the OLS model above. We can combine these approaches with RK.</p>
<p>We will set up a <code>gstat</code> object with the linear regression model. When we plot the variogram we are seeing the residuals from that regression. They have some spatial structure. In OLS that is bad (violates independence). For RK, this is good! It means we can use that structure to improve the prediction.</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="probabilistic-interpolation-regression-kriging.html#cb306-1" tabindex="-1"></a>omGstat <span class="ot">&lt;-</span> <span class="fu">gstat</span>(<span class="at">id =</span> <span class="st">&quot;omModel&quot;</span>, <span class="at">formula =</span> om <span class="sc">~</span> sqrt_dist <span class="sc">+</span> soil, </span>
<span id="cb306-2"><a href="probabilistic-interpolation-regression-kriging.html#cb306-2" tabindex="-1"></a>                 <span class="at">data =</span> meusePoints_sf)</span>
<span id="cb306-3"><a href="probabilistic-interpolation-regression-kriging.html#cb306-3" tabindex="-1"></a>omGstat_obsVariogram <span class="ot">&lt;-</span> <span class="fu">variogram</span>(omGstat)</span>
<span id="cb306-4"><a href="probabilistic-interpolation-regression-kriging.html#cb306-4" tabindex="-1"></a><span class="fu">plot</span>(omGstat_obsVariogram,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">&quot;black&quot;</span>,</span>
<span id="cb306-5"><a href="probabilistic-interpolation-regression-kriging.html#cb306-5" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">&quot;Semivariance (&quot;</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">&quot;)&quot;</span>),</span>
<span id="cb306-6"><a href="probabilistic-interpolation-regression-kriging.html#cb306-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Distance (m)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Model Residuals&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-19-1.png" alt="" width="672" /></p>
<p>Ok. Let’s look at this. It’s not a severe variogram. But you can see that the semivariance goes from a nugget of about four to a sill of about six. I.e., there is spatial structure in this model that we can leverage and that should improve our predictions.</p>
<p>Thus, let’s fit a theoretical model to the <code>omGstat_obsVariogram</code> variogram. I’ll use a Gaussian model but you could make a good case here for an Exponential model.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="probabilistic-interpolation-regression-kriging.html#cb307-1" tabindex="-1"></a>omGau_fittedVariogram <span class="ot">&lt;-</span> <span class="fu">fit.variogram</span>(omGstat_obsVariogram, <span class="fu">vgm</span>(<span class="at">psill =</span> <span class="dv">6</span>, <span class="at">model =</span> <span class="st">&quot;Gau&quot;</span>, <span class="at">range =</span> <span class="dv">500</span>, <span class="at">nugget =</span> <span class="dv">4</span>))</span>
<span id="cb307-2"><a href="probabilistic-interpolation-regression-kriging.html#cb307-2" tabindex="-1"></a></span>
<span id="cb307-3"><a href="probabilistic-interpolation-regression-kriging.html#cb307-3" tabindex="-1"></a><span class="fu">plot</span>(omGstat_obsVariogram, omGau_fittedVariogram,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.5</span>,<span class="at">col=</span><span class="st">&quot;black&quot;</span>,</span>
<span id="cb307-4"><a href="probabilistic-interpolation-regression-kriging.html#cb307-4" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(<span class="st">&quot;Semivariance (&quot;</span><span class="sc">*</span>gamma<span class="sc">*</span><span class="st">&quot;)&quot;</span>),</span>
<span id="cb307-5"><a href="probabilistic-interpolation-regression-kriging.html#cb307-5" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Distance (m)&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Model Residuals&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-20-1.png" alt="" width="672" /></p>
<p>Now we can update the <code>gstat</code> object with that variogram model. And use it to make a prediction.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="probabilistic-interpolation-regression-kriging.html#cb308-1" tabindex="-1"></a><span class="co"># Update the gstat object with the variogram:</span></span>
<span id="cb308-2"><a href="probabilistic-interpolation-regression-kriging.html#cb308-2" tabindex="-1"></a>omGstat_w_variogram <span class="ot">&lt;-</span> <span class="fu">gstat</span>(omGstat, <span class="at">id=</span><span class="st">&quot;omModel&quot;</span>, <span class="at">model=</span>omGau_fittedVariogram)</span>
<span id="cb308-3"><a href="probabilistic-interpolation-regression-kriging.html#cb308-3" tabindex="-1"></a><span class="co"># And predict</span></span>
<span id="cb308-4"><a href="probabilistic-interpolation-regression-kriging.html#cb308-4" tabindex="-1"></a>omHat_sf <span class="ot">&lt;-</span> <span class="fu">predict</span>(omGstat_w_variogram, <span class="at">newdata =</span> meuseGrid_sf)</span></code></pre></div>
<pre><code>## [using universal kriging]</code></pre>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="probabilistic-interpolation-regression-kriging.html#cb310-1" tabindex="-1"></a>omHat_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 3103 features and 2 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 178460 ymin: 329620 xmax: 181540 ymax: 333740
## Projected CRS: Amersfoort / RD New
## First 10 features:
##    omModel.pred omModel.var              geometry
## 1      14.33925    5.370485 POINT (181180 333740)
## 2      14.38783    5.207100 POINT (181140 333700)
## 3      13.21201    5.157301 POINT (181180 333700)
## 4      12.16400    5.172975 POINT (181220 333700)
## 5      14.40786    5.072085 POINT (181100 333660)
## 6      13.24575    5.008216 POINT (181140 333660)
## 7      12.37960    5.012550 POINT (181180 333660)
## 8      11.85536    5.056316 POINT (181220 333660)
## 9      13.99688    4.937390 POINT (181060 333620)
## 10     13.24907    4.889661 POINT (181100 333620)</code></pre>
<p>We have made a new object <code>omHat_sf</code> that has the predictions and the variance from the RK. It’s an <code>sf</code> object (because <code>meuseGridSF</code> is also <code>sf</code>). Let’s make them into <code>SpatRasers</code> to make the plots prettier.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="probabilistic-interpolation-regression-kriging.html#cb312-1" tabindex="-1"></a>omHat_rast <span class="ot">&lt;-</span> <span class="fu">sf_2_rast</span>(omHat_sf,<span class="at">variable2get =</span> <span class="st">&quot;omModel.pred&quot;</span>)</span>
<span id="cb312-2"><a href="probabilistic-interpolation-regression-kriging.html#cb312-2" tabindex="-1"></a>omHat_rast</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 104, 78, 1  (nrow, ncol, nlyr)
## resolution  : 40, 40  (x, y)
## extent      : 178440, 181560, 329600, 333760  (xmin, xmax, ymin, ymax)
## coord. ref. : Amersfoort / RD New (EPSG:28992) 
## source(s)   : memory
## name        : omModel.pred 
## min value   :     1.891323 
## max value   :    14.407855</code></pre>
<p>And plot:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="probabilistic-interpolation-regression-kriging.html#cb314-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb314-2"><a href="probabilistic-interpolation-regression-kriging.html#cb314-2" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> omHat_rast,</span>
<span id="cb314-3"><a href="probabilistic-interpolation-regression-kriging.html#cb314-3" tabindex="-1"></a>                           <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill=</span>omModel.pred)) <span class="sc">+</span></span>
<span id="cb314-4"><a href="probabilistic-interpolation-regression-kriging.html#cb314-4" tabindex="-1"></a>  <span class="fu">scale_fill_terrain_c</span>() <span class="sc">+</span></span>
<span id="cb314-5"><a href="probabilistic-interpolation-regression-kriging.html#cb314-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Organic Matter (%)&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-23-1.png" alt="" width="672" /></p>
<p>And variance around the predictions:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="probabilistic-interpolation-regression-kriging.html#cb315-1" tabindex="-1"></a>omHatVar_rast <span class="ot">&lt;-</span> <span class="fu">sf_2_rast</span>(omHat_sf,<span class="at">variable2get =</span> <span class="st">&quot;omModel.var&quot;</span>)</span>
<span id="cb315-2"><a href="probabilistic-interpolation-regression-kriging.html#cb315-2" tabindex="-1"></a><span class="co"># take the square root of variance to create standard deviation (units match then)</span></span>
<span id="cb315-3"><a href="probabilistic-interpolation-regression-kriging.html#cb315-3" tabindex="-1"></a>omHatVar_rast <span class="ot">&lt;-</span> omHatVar_rast <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">omModel.var.sqrt =</span> <span class="fu">sqrt</span>(omModel.var))</span>
<span id="cb315-4"><a href="probabilistic-interpolation-regression-kriging.html#cb315-4" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_spatraster</span>(<span class="at">data =</span> omHatVar_rast,</span>
<span id="cb315-5"><a href="probabilistic-interpolation-regression-kriging.html#cb315-5" tabindex="-1"></a>                           <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill=</span>omModel.var.sqrt)) <span class="sc">+</span></span>
<span id="cb315-6"><a href="probabilistic-interpolation-regression-kriging.html#cb315-6" tabindex="-1"></a>  <span class="fu">scale_fill_terrain_c</span>() <span class="sc">+</span></span>
<span id="cb315-7"><a href="probabilistic-interpolation-regression-kriging.html#cb315-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Organic Matter Variance (%)&quot;</span>)</span></code></pre></div>
<p><img src="06bGeostatsRegressionKriging_files/figure-html/unnamed-chunk-24-1.png" alt="" width="672" /></p>
<p>The RK approach looks quite a bit different than the OLS prediction. Now our job is to look at the differences carefully and assess skill.</p>
</div>
</div>
<div id="your-work-7" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Your Work<a href="probabilistic-interpolation-regression-kriging.html#your-work-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>None. This is kind of an add on to introduce you to RK. But you should be able to apply by following the workflow above. I suggest taking some time to figure out how to use <code>gstat.cv</code> and perform k-fold cross validation on the <code>omGstat_w_variogram</code> object and object with just the linear model (<code>omGstat</code>). Compare the skill of a k-fold cross validated OLS model and the k-fold cross validated RK model. Use R<span class="math inline">\(^2\)</span> and RMSE as your measures of skill. Did the RK approach improve the predictions?</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probabilistic-interpolation-kriging.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aside-kriging-variance-by-hand.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
